import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const Montserra = Montserrat({
  variable: "--font-montserrat",
  subsets: ["cyrillic"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Montserra.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
